# Generated by Django 4.1.7 on 2023-03-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характер отказа',
                'verbose_name_plural': 'Характер отказа',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=18, verbose_name='Зав № техники')),
                ('engine_number', models.CharField(max_length=10, verbose_name='Зав № двигателя')),
                ('trans_number', models.CharField(max_length=10, verbose_name='Зав. № трансмиссии')),
                ('leadBR_number', models.CharField(max_length=10, verbose_name='Зав № ведущего моста')),
                ('controlBR_number', models.CharField(max_length=10, verbose_name='Зав № управляемого моста')),
                ('contract_Date', models.CharField(max_length=20, verbose_name='Дата и номер договора')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки')),
                ('adress', models.CharField(max_length=120, verbose_name='Адрес доставки')),
                ('complectation', models.CharField(max_length=120, verbose_name='Комплектация')),
                ('client', models.CharField(max_length=64, verbose_name='Покупатель')),
                ('user', models.CharField(default=models.CharField(max_length=64, verbose_name='Покупатель'), max_length=64, verbose_name='Грузополучатель')),
                ('user_adress', models.CharField(default=models.CharField(max_length=120, verbose_name='Адрес доставки'), max_length=120, verbose_name='Адрес поставки')),
            ],
            options={
                'verbose_name': 'Погрузчик',
                'verbose_name_plural': 'Погрузчики',
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('discription', models.CharField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель погрузчика',
                'verbose_name_plural': 'Модели погрузчиков',
            },
        ),
        migrations.CreateModel(
            name='ControlBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляющего моста',
                'verbose_name_plural': 'Модели управляющего моста',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателя',
            },
        ),
        migrations.CreateModel(
            name='LeadBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='MaintainceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=32, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('discription', models.CharField(max_length=120, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Transmition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('discription', models.CharField(blank=True, max_length=16, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Maintains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала ТО')),
                ('order_number', models.CharField(max_length=10, verbose_name='Номер наряд-заказа')),
                ('order_date', models.DateTimeField(verbose_name='Дата окончания ТО')),
                ('car_work_time', models.FloatField(default=0, verbose_name='Время наработки (м\\час)')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicecompany', verbose_name='Сервисная компания')),
                ('maintains_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.maintaincetype', verbose_name='Вид ТО')),
                ('repaired_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.car', verbose_name='Зав. № машины')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Техническое обслуживание',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejection', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м\\час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.brokecharacter', verbose_name='Узел отказа')),
                ('machine_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.car', verbose_name='Зав. № машины')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламации',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-date_rejection'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='controlBR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.controlbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.engine', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='leadBR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.leadbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='service.carmodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная кампания'),
        ),
        migrations.AddField(
            model_name='car',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.transmition', verbose_name='Модель трансмиссии'),
        ),
    ]
