# Generated by Django 4.1.7 on 2023-02-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokecharacter',
            options={'verbose_name': 'Характер отказа', 'verbose_name_plural': 'Характер отказа'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-shipment_date'], 'verbose_name': 'Погрузчик', 'verbose_name_plural': 'Погрузчики'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель погрузчика', 'verbose_name_plural': 'Модели погрузчиков'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date_rejection'], 'verbose_name': 'Рекламации', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='controlbridge',
            options={'verbose_name': 'Модель управляющего моста', 'verbose_name_plural': 'Модели управляющего моста'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателя'},
        ),
        migrations.AlterModelOptions(
            name='leadbridge',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='maintaincetype',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.AlterModelOptions(
            name='maintains',
            options={'ordering': ['-order_date'], 'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Техническое обслуживание'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='repairtype',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='transmition',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.CharField(default=models.CharField(max_length=64, verbose_name='Покупатель'), max_length=64, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='adress',
            field=models.CharField(max_length=120, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(max_length=64, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='controlBR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.controlbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='car',
            name='controlBR_number',
            field=models.CharField(max_length=10, verbose_name='Зав № управляемого моста'),
        ),
    ]
