# Generated by Django 4.1.7 on 2023-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_brokecharacter_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_adress',
            field=models.CharField(default=models.CharField(max_length=120, verbose_name='Адрес доставки'), max_length=120, verbose_name='Адрес поставки'),
        ),
    ]
